import type { DataCenterImpact, DpeBreakdown, EnergySector, Territory, TerritorySummary } from "./types";
import { getCommuneByCode, makeEstimatedTerritory } from "./communes";

type TerritorySeed = Omit<Territory, "history" | "sectors" | "dpe" | "dataCenterImpact"> & {
  sectorShares: Record<EnergySector, number>;
  dpeShares: DpeBreakdown["share"][];
  dataCenterMwh: number;
  gridPressure: DataCenterImpact["gridPressure"];
  heatReusePotential: DataCenterImpact["heatReusePotential"];
  waterStress: DataCenterImpact["waterStress"];
  renewableContractShare: number;
  pueTarget: number;
};

const dpeLabels: DpeBreakdown["label"][] = ["A", "B", "C", "D", "E", "F", "G"];

function makeHistory(consumptionMwh: number, evolutionPercent: number, emissionsTco2e: number) {
  const base = Math.round(consumptionMwh / (1 + evolutionPercent / 100));
  const emissionBase = Math.round(emissionsTco2e / (1 + evolutionPercent / 120));
  const steps = [1, 0.94, 0.985, 0.965, 0.945, consumptionMwh / base];

  return steps.map((factor, index) => ({
    year: 2019 + index,
    consumptionMwh: Math.round(base * factor),
    emissionsTco2e: Math.round(emissionBase * (factor - index * 0.006)),
  }));
}

function makeTerritory(seed: TerritorySeed): Territory {
  const dataCenterShare = Number(((seed.dataCenterMwh / seed.consumptionMwh) * 100).toFixed(1));

  return {
    ...seed,
    history: makeHistory(seed.consumptionMwh, seed.evolutionPercent, seed.emissionsTco2e),
    sectors: Object.entries(seed.sectorShares).map(([sector, share]) => ({
      sector: sector as EnergySector,
      share,
      consumptionMwh: Math.round((seed.consumptionMwh * share) / 100),
    })),
    dpe: dpeLabels.map((label, index) => ({ label, share: seed.dpeShares[index] })),
    dataCenterImpact: {
      estimatedAnnualMwh: seed.dataCenterMwh,
      shareOfTerritoryConsumption: dataCenterShare,
      gridPressure: seed.gridPressure,
      heatReusePotential: seed.heatReusePotential,
      waterStress: seed.waterStress,
      renewableContractShare: seed.renewableContractShare,
      pueTarget: seed.pueTarget,
      notes: [
        "Estimation de démonstration à remplacer par des données opérateurs, raccordement RTE/Enedis et bilans environnementaux.",
        "Suivre la puissance appelée, l'origine de l'électricité, le PUE, le refroidissement et la récupération de chaleur.",
        "Croiser les nouveaux projets avec la disponibilité réseau et les besoins locaux de chaleur bas carbone.",
      ],
    },
  };
}

export const territories: Territory[] = [
  makeTerritory({
    code: "75056",
    name: "Paris",
    department: "Paris",
    region: "Ile-de-France",
    population: 2133111,
    surfaceKm2: 105.4,
    consumptionMwh: 26640000,
    evolutionPercent: -8.7,
    emissionsTco2e: 3390000,
    renewableShare: 14,
    energyMix: { electricite: 41, gaz: 34, chaleur: 18, froid: 2, carburants: 5 },
    sectorShares: { tertiaire: 39, residentiel: 34, transport: 8, industrie: 6, agriculture: 1, numerique: 12 },
    dpeShares: [3, 7, 18, 31, 24, 11, 6],
    actions: [
      "Prioriser la rénovation des copropriétés construites avant 1975.",
      "Accélérer le raccordement chaleur renouvelable des grands sites tertiaires.",
      "Encadrer les charges numériques par contrats d'électricité bas carbone et récupération de chaleur.",
    ],
    dataCenterMwh: 3197000,
    gridPressure: "forte",
    heatReusePotential: "eleve",
    waterStress: "modere",
    renewableContractShare: 42,
    pueTarget: 1.25,
  }),
  makeTerritory({
    code: "69381",
    name: "Lyon",
    department: "Rhône",
    region: "Auvergne-Rhône-Alpes",
    population: 522969,
    surfaceKm2: 47.9,
    consumptionMwh: 6640000,
    evolutionPercent: -5.2,
    emissionsTco2e: 812000,
    renewableShare: 19,
    energyMix: { electricite: 43, gaz: 32, chaleur: 16, froid: 1, carburants: 8 },
    sectorShares: { residentiel: 35, tertiaire: 32, industrie: 13, transport: 7, agriculture: 1, numerique: 12 },
    dpeShares: [5, 10, 22, 30, 21, 8, 4],
    actions: [
      "Renforcer les contrats de performance énergétique du parc tertiaire.",
      "Comparer les quartiers à forte densité gaz avec les opportunités réseau de chaleur.",
      "Valoriser la chaleur fatale numérique vers les réseaux urbains denses.",
    ],
    dataCenterMwh: 797000,
    gridPressure: "forte",
    heatReusePotential: "eleve",
    waterStress: "modere",
    renewableContractShare: 46,
    pueTarget: 1.27,
  }),
  makeTerritory({
    code: "13055",
    name: "Marseille",
    department: "Bouches-du-Rhône",
    region: "Provence-Alpes-Côte d'Azur",
    population: 873076,
    surfaceKm2: 240.6,
    consumptionMwh: 8840000,
    evolutionPercent: -3.8,
    emissionsTco2e: 1184000,
    renewableShare: 17,
    energyMix: { electricite: 48, gaz: 24, chaleur: 7, froid: 3, carburants: 18 },
    sectorShares: { residentiel: 34, tertiaire: 26, transport: 17, industrie: 10, agriculture: 1, numerique: 12 },
    dpeShares: [4, 8, 20, 28, 24, 10, 6],
    actions: [
      "Prioriser confort d'été et isolation des logements collectifs.",
      "Déployer solaire et autoconsommation sur foncier public disponible.",
      "Surveiller refroidissement et eau sur les sites numériques littoraux.",
    ],
    dataCenterMwh: 1061000,
    gridPressure: "forte",
    heatReusePotential: "moyen",
    waterStress: "eleve",
    renewableContractShare: 38,
    pueTarget: 1.3,
  }),
  makeTerritory({
    code: "31555",
    name: "Toulouse",
    department: "Haute-Garonne",
    region: "Occitanie",
    population: 504078,
    surfaceKm2: 118.3,
    consumptionMwh: 5360000,
    evolutionPercent: -4.6,
    emissionsTco2e: 642000,
    renewableShare: 22,
    energyMix: { electricite: 46, gaz: 28, chaleur: 10, froid: 1, carburants: 15 },
    sectorShares: { residentiel: 34, tertiaire: 31, industrie: 14, transport: 10, agriculture: 2, numerique: 9 },
    dpeShares: [6, 12, 24, 29, 19, 7, 3],
    actions: [
      "Articuler rénovation résidentielle et croissance démographique.",
      "Identifier les sites industriels capables d'effacement électrique.",
      "Evaluer les nouveaux besoins numériques avec les capacités réseau locales.",
    ],
    dataCenterMwh: 482000,
    gridPressure: "moderee",
    heatReusePotential: "moyen",
    waterStress: "eleve",
    renewableContractShare: 44,
    pueTarget: 1.28,
  }),
  makeTerritory({
    code: "06088",
    name: "Nice",
    department: "Alpes-Maritimes",
    region: "Provence-Alpes-Côte d'Azur",
    population: 348085,
    surfaceKm2: 71.9,
    consumptionMwh: 3520000,
    evolutionPercent: -2.9,
    emissionsTco2e: 476000,
    renewableShare: 16,
    energyMix: { electricite: 53, gaz: 22, chaleur: 4, froid: 4, carburants: 17 },
    sectorShares: { residentiel: 38, tertiaire: 33, transport: 15, industrie: 5, agriculture: 1, numerique: 8 },
    dpeShares: [4, 9, 22, 30, 22, 9, 4],
    actions: ["Réduire les pointes de climatisation estivale.", "Cibler les hôtels et commerces à forte intensité froid.", "Conditionner les projets data centers à une stratégie eau et chaleur."],
    dataCenterMwh: 282000,
    gridPressure: "moderee",
    heatReusePotential: "faible",
    waterStress: "eleve",
    renewableContractShare: 35,
    pueTarget: 1.32,
  }),
  makeTerritory({
    code: "44109",
    name: "Nantes",
    department: "Loire-Atlantique",
    region: "Pays de la Loire",
    population: 323204,
    surfaceKm2: 65.2,
    consumptionMwh: 2960000,
    evolutionPercent: -6.1,
    emissionsTco2e: 342000,
    renewableShare: 24,
    energyMix: { electricite: 45, gaz: 30, chaleur: 12, froid: 1, carburants: 12 },
    sectorShares: { residentiel: 36, tertiaire: 34, industrie: 9, transport: 9, agriculture: 1, numerique: 11 },
    dpeShares: [7, 13, 25, 29, 17, 6, 3],
    actions: ["Etendre les réseaux de chaleur renouvelable.", "Suivre les zones tertiaires à forte consommation électrique.", "Utiliser la chaleur fatale numérique pour équipements publics proches."],
    dataCenterMwh: 326000,
    gridPressure: "moderee",
    heatReusePotential: "moyen",
    waterStress: "faible",
    renewableContractShare: 51,
    pueTarget: 1.24,
  }),
  makeTerritory({
    code: "67482",
    name: "Strasbourg",
    department: "Bas-Rhin",
    region: "Grand Est",
    population: 291313,
    surfaceKm2: 78.3,
    consumptionMwh: 3120000,
    evolutionPercent: -7.4,
    emissionsTco2e: 388000,
    renewableShare: 27,
    energyMix: { electricite: 39, gaz: 31, chaleur: 20, froid: 1, carburants: 9 },
    sectorShares: { residentiel: 35, tertiaire: 31, industrie: 13, transport: 8, agriculture: 1, numerique: 12 },
    dpeShares: [6, 11, 23, 30, 19, 7, 4],
    actions: ["Renforcer chaleur renouvelable et récupération industrielle.", "Prioriser rénovation thermique du parc ancien.", "Raccorder les charges numériques aux boucles de chaleur disponibles."],
    dataCenterMwh: 374000,
    gridPressure: "moderee",
    heatReusePotential: "eleve",
    waterStress: "faible",
    renewableContractShare: 56,
    pueTarget: 1.23,
  }),
  makeTerritory({
    code: "33063",
    name: "Bordeaux",
    department: "Gironde",
    region: "Nouvelle-Aquitaine",
    population: 261804,
    surfaceKm2: 49.4,
    consumptionMwh: 2680000,
    evolutionPercent: -4.1,
    emissionsTco2e: 318000,
    renewableShare: 21,
    energyMix: { electricite: 47, gaz: 29, chaleur: 8, froid: 1, carburants: 15 },
    sectorShares: { residentiel: 37, tertiaire: 34, industrie: 8, transport: 10, agriculture: 1, numerique: 10 },
    dpeShares: [6, 12, 25, 28, 18, 7, 4],
    actions: ["Accélérer rénovation des logements chauffés au gaz.", "Développer solaire en toiture et ombrières.", "Intégrer les data centers au pilotage des pointes électriques."],
    dataCenterMwh: 268000,
    gridPressure: "moderee",
    heatReusePotential: "moyen",
    waterStress: "modere",
    renewableContractShare: 47,
    pueTarget: 1.26,
  }),
  makeTerritory({
    code: "35238",
    name: "Rennes",
    department: "Ille-et-Vilaine",
    region: "Bretagne",
    population: 225081,
    surfaceKm2: 50.4,
    consumptionMwh: 2140000,
    evolutionPercent: -5.8,
    emissionsTco2e: 246000,
    renewableShare: 25,
    energyMix: { electricite: 48, gaz: 27, chaleur: 12, froid: 1, carburants: 12 },
    sectorShares: { residentiel: 36, tertiaire: 32, industrie: 9, transport: 8, agriculture: 2, numerique: 13 },
    dpeShares: [8, 14, 25, 28, 16, 6, 3],
    actions: ["Piloter le développement numérique avec contrats renouvelables.", "Renforcer la sobriété tertiaire sur campus et administrations.", "Capter la chaleur fatale vers réseaux de quartier."],
    dataCenterMwh: 278000,
    gridPressure: "moderee",
    heatReusePotential: "moyen",
    waterStress: "faible",
    renewableContractShare: 58,
    pueTarget: 1.22,
  }),
  makeTerritory({
    code: "38185",
    name: "Grenoble",
    department: "Isère",
    region: "Auvergne-Rhône-Alpes",
    population: 157477,
    surfaceKm2: 18.1,
    consumptionMwh: 1820000,
    evolutionPercent: -9.2,
    emissionsTco2e: 198000,
    renewableShare: 34,
    energyMix: { electricite: 42, gaz: 23, chaleur: 23, froid: 1, carburants: 11 },
    sectorShares: { residentiel: 34, tertiaire: 30, industrie: 11, transport: 7, agriculture: 1, numerique: 17 },
    dpeShares: [8, 15, 27, 27, 15, 5, 3],
    actions: ["Amplifier chaleur renouvelable et efficacité du bâti collectif.", "Mobiliser les laboratoires sur sobriété numérique.", "Exiger récupération de chaleur pour les salles serveurs et calcul."],
    dataCenterMwh: 309000,
    gridPressure: "moderee",
    heatReusePotential: "eleve",
    waterStress: "faible",
    renewableContractShare: 63,
    pueTarget: 1.2,
  }),
  makeTerritory({
    code: "34172",
    name: "Montpellier",
    department: "Hérault",
    region: "Occitanie",
    population: 302454,
    surfaceKm2: 56.9,
    consumptionMwh: 2460000,
    evolutionPercent: -3.2,
    emissionsTco2e: 298000,
    renewableShare: 23,
    energyMix: { electricite: 52, gaz: 22, chaleur: 7, froid: 2, carburants: 17 },
    sectorShares: { residentiel: 39, tertiaire: 33, industrie: 5, transport: 11, agriculture: 2, numerique: 10 },
    dpeShares: [7, 13, 24, 28, 18, 7, 3],
    actions: ["Traiter le confort d'été sans hausse incontrôlée de la climatisation.", "Développer solaire local et flexibilité électrique.", "Evaluer refroidissement data centers en contexte de stress hydrique."],
    dataCenterMwh: 246000,
    gridPressure: "moderee",
    heatReusePotential: "faible",
    waterStress: "eleve",
    renewableContractShare: 49,
    pueTarget: 1.29,
  }),
  makeTerritory({
    code: "59350",
    name: "Lille",
    department: "Nord",
    region: "Hauts-de-France",
    population: 236234,
    surfaceKm2: 34.8,
    consumptionMwh: 2380000,
    evolutionPercent: -6.9,
    emissionsTco2e: 312000,
    renewableShare: 18,
    energyMix: { electricite: 41, gaz: 33, chaleur: 14, froid: 1, carburants: 11 },
    sectorShares: { residentiel: 36, tertiaire: 33, industrie: 10, transport: 8, agriculture: 1, numerique: 12 },
    dpeShares: [5, 10, 22, 30, 21, 8, 4],
    actions: ["Rénover le parc ancien et réduire la dépendance gaz.", "Mutualiser chaleur industrielle et numérique.", "Sécuriser les raccordements électriques des nouveaux usages."],
    dataCenterMwh: 286000,
    gridPressure: "moderee",
    heatReusePotential: "eleve",
    waterStress: "faible",
    renewableContractShare: 45,
    pueTarget: 1.24,
  }),
  makeTerritory({
    code: "93066",
    name: "Saint-Denis",
    department: "Seine-Saint-Denis",
    region: "Ile-de-France",
    population: 113116,
    surfaceKm2: 12.4,
    consumptionMwh: 1920000,
    evolutionPercent: -3.5,
    emissionsTco2e: 245000,
    renewableShare: 15,
    energyMix: { electricite: 49, gaz: 27, chaleur: 15, froid: 2, carburants: 7 },
    sectorShares: { residentiel: 27, tertiaire: 36, industrie: 8, transport: 5, agriculture: 1, numerique: 23 },
    dpeShares: [4, 8, 19, 29, 24, 10, 6],
    actions: ["Prioriser rénovation des logements collectifs énergivores.", "Raccorder les grands sites numériques aux réseaux de chaleur.", "Suivre l'impact réseau des charges électriques concentrées."],
    dataCenterMwh: 442000,
    gridPressure: "forte",
    heatReusePotential: "eleve",
    waterStress: "modere",
    renewableContractShare: 41,
    pueTarget: 1.23,
  }),
  makeTerritory({
    code: "91120",
    name: "Palaiseau",
    department: "Essonne",
    region: "Ile-de-France",
    population: 35631,
    surfaceKm2: 11.5,
    consumptionMwh: 980000,
    evolutionPercent: 6.4,
    emissionsTco2e: 112000,
    renewableShare: 18,
    energyMix: { electricite: 58, gaz: 20, chaleur: 8, froid: 2, carburants: 12 },
    sectorShares: { residentiel: 23, tertiaire: 25, industrie: 8, transport: 5, agriculture: 1, numerique: 38 },
    dpeShares: [10, 16, 26, 25, 14, 6, 3],
    actions: ["Créer un suivi spécifique campus, calcul intensif et data centers.", "Négocier effacement et flexibilité des charges numériques.", "Orienter la chaleur fatale vers logements et équipements voisins."],
    dataCenterMwh: 372000,
    gridPressure: "forte",
    heatReusePotential: "eleve",
    waterStress: "modere",
    renewableContractShare: 55,
    pueTarget: 1.18,
  }),
  makeTerritory({
    code: "27701",
    name: "Val-de-Reuil",
    department: "Eure",
    region: "Normandie",
    population: 13243,
    surfaceKm2: 25.6,
    consumptionMwh: 820000,
    evolutionPercent: 11.8,
    emissionsTco2e: 98000,
    renewableShare: 20,
    energyMix: { electricite: 61, gaz: 18, chaleur: 6, froid: 2, carburants: 13 },
    sectorShares: { residentiel: 14, tertiaire: 18, industrie: 19, transport: 4, agriculture: 1, numerique: 44 },
    dpeShares: [7, 13, 24, 28, 18, 7, 3],
    actions: ["Suivre les extensions data centers dans la planification électrique.", "Récupérer la chaleur fatale vers zones d'activité et équipements.", "Documenter eau, refroidissement et garanties d'origine renouvelable."],
    dataCenterMwh: 361000,
    gridPressure: "forte",
    heatReusePotential: "moyen",
    waterStress: "faible",
    renewableContractShare: 60,
    pueTarget: 1.2,
  }),
  makeTerritory({
    code: "59183",
    name: "Dunkerque",
    department: "Nord",
    region: "Hauts-de-France",
    population: 86865,
    surfaceKm2: 43.9,
    consumptionMwh: 6120000,
    evolutionPercent: -1.2,
    emissionsTco2e: 912000,
    renewableShare: 16,
    energyMix: { electricite: 39, gaz: 28, chaleur: 11, froid: 1, carburants: 21 },
    sectorShares: { residentiel: 9, tertiaire: 11, industrie: 65, transport: 9, agriculture: 1, numerique: 5 },
    dpeShares: [4, 9, 21, 30, 22, 9, 5],
    actions: ["Prioriser décarbonation industrielle et chaleur fatale.", "Coordonner hydrogène, électrification et capacités réseau.", "Comparer l'impact numérique avec les charges industrielles dominantes."],
    dataCenterMwh: 306000,
    gridPressure: "forte",
    heatReusePotential: "eleve",
    waterStress: "faible",
    renewableContractShare: 37,
    pueTarget: 1.25,
  }),
];

export function listTerritories(): TerritorySummary[] {
  return territories.map(({ code, name, department, region, population, consumptionMwh, evolutionPercent }) => ({
    code,
    name,
    department,
    region,
    population,
    consumptionMwh,
    evolutionPercent,
  }));
}

export async function getTerritory(code: string): Promise<Territory | null> {
  const territory = territories.find((item) => item.code === code);

  if (territory) {
    return territory;
  }

  const commune = await getCommuneByCode(code);

  return commune ? makeEstimatedTerritory(commune) : null;
}

export function compareTerritories(codes: string[]) {
  const wanted = new Set(codes);
  return territories.filter((territory) => wanted.has(territory.code));
}
